# Generated by Django 4.1 on 2022-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KerberosData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kerberos', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('hostel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='registrationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kerberos', models.CharField(max_length=9, unique=True)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
