# Generated by Django 4.1 on 2022-09-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='forgotToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kerberos', models.CharField(max_length=9, unique=True)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
