# Generated by Django 4.1 on 2022-09-07 16:56

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=800)),
                ('image_1', models.ImageField(upload_to=app.models.get_image_path)),
                ('image_2', models.ImageField(blank=True, upload_to=app.models.get_image_path)),
                ('image_3', models.ImageField(blank=True, upload_to=app.models.get_image_path)),
                ('public', models.BooleanField(default=True)),
                ('likes', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.intro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
    ]
