# Generated by Django 4.1 on 2022-09-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_intro_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='representative',
            field=models.BooleanField(default=False),
        ),
    ]
