# Generated by Django 4.1 on 2022-10-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_intro_representative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intro',
            old_name='representative',
            new_name='approved',
        ),
    ]
